### ISSUE TITLE
UnboundLocalError at /cms/home/venue/reorder/3/: local variable 'update_value' referenced before assignment

### ISSUE THREAD

**Issue by janbaykara** [elton2048/wagtail-orderable#38]
Some details, and debugging comments and solution questions at the bottom of the OP:

### Packages

wagtail-orderable 1.1.0
wagtail 3.0.3
django 4.0.7

### Full stack error

```
[08/Sep/2022 16:00:25] "GET /cms/home/venue/reorder/3/?after=2 HTTP/1.1" 500 74627
Internal Server Error: /cms/home/venue/reorder/3/
Traceback (most recent call last):
  File "/home/vscode/.local/share/virtualenvs/workspace-dqq3IVyd/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/vscode/.local/share/virtualenvs/workspace-dqq3IVyd/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vscode/.local/share/virtualenvs/workspace-dqq3IVyd/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/vscode/.local/share/virtualenvs/workspace-dqq3IVyd/lib/python3.9/site-packages/wagtail/admin/urls/__init__.py", line 161, in wrapper
    return view_func(request, *args, **kwargs)
  File "/home/vscode/.local/share/virtualenvs/workspace-dqq3IVyd/lib/python3.9/site-packages/wagtail/admin/auth.py", line 182, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/vscode/.local/share/virtualenvs/workspace-dqq3IVyd/lib/python3.9/site-packages/wagtailorderable/modeladmin/mixins.py", line 196, in reorder_view
    qs.update(**{self.sort_order_field: update_value})
UnboundLocalError: local variable 'update_value' referenced before assignment
Internal Server Error: /cms/home/venue/reorder/3/
Traceback (most recent call last):
  File "/home/vscode/.local/share/virtualenvs/workspace-dqq3IVyd/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/vscode/.local/share/virtualenvs/workspace-dqq3IVyd/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vscode/.local/share/virtualenvs/workspace-dqq3IVyd/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/vscode/.local/share/virtualenvs/workspace-dqq3IVyd/lib/python3.9/site-packages/wagtail/admin/urls/__init__.py", line 161, in wrapper
    return view_func(request, *args, **kwargs)
  File "/home/vscode/.local/share/virtualenvs/workspace-dqq3IVyd/lib/python3.9/site-packages/wagtail/admin/auth.py", line 182, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/vscode/.local/share/virtualenvs/workspace-dqq3IVyd/lib/python3.9/site-packages/wagtailorderable/modeladmin/mixins.py", line 196, in reorder_view
    qs.update(**{self.sort_order_field: update_value})
UnboundLocalError: local variable 'update_value' referenced before assignment
```

## Relevant code

https://github.com/elton2048/wagtail-orderable/blob/4869d35edacbb42753318b1dc2a7c7f826bb6696/wagtailorderable/modeladmin/mixins.py#L178-L196

## Debugging

Printing `print(position, old_position)` in the above code prints `0, 0`.

Looking at my database, I see that the `sort_order` column for all Venue records is NULL, and this is why position and old_position and so on are defaulting to 0. 

So my question is: how are we meant to initialise the database with an arbitrary sort order, so that the ordering function works?

**Comment by janbaykara** [comment]
I guess what needs to be done is for sort_order to be non-nullable and to autoincrement, so that model records migrated to Orderable will not show up as Null on install?

**Comment by janbaykara** [comment]
I solved this by adding a manual migration operation that runs straight after adding this package's relevant fields:

```python
# Generated by Django 4.0.7 on 2022-09-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0094_alter_festival_page_body'),
    ]

    def init_sort_order_for_orderables(apps, schema_editor):
        try:
            '''
            We're loading the live model so that we have
            access to the venue.get_sort_order_max method
            '''
            from home.models import Venue
            db_alias = schema_editor.connection.alias
            venues = Venue.objects.using(
                db_alias).filter(sort_order__isnull=True)
            for venue in venues:
                venue.sort_order = venue.get_sort_order_max() + 1
                venue.save()
        except:
            '''
            It might be that we uninstalled this Orderable package
            in which case this operation is unecessary anyway!
            '''
            pass

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='venue',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(init_sort_order_for_orderables, lambda x, y: None)
    ]
```

**Comment by janbaykara** [comment]
Would be cool if this package provided some docs on this issue, and maybe a helper function like the above.

**Comment by rharriso** [comment]
This issue is caused by this section of code:

https://github.com/elton2048/wagtail-orderable/blob/master/wagtailorderable/modeladmin/mixins.py#L178-L196C45

I see a couple issues with this.

1. the default value for `sort_order` is `null`
2. `update_value` is initialized within an else-less if.

The default behavior of these two then is to throw an exception that can't be recovered from.

I've adjusted the property on in my usage in this way:

```python
class TopProduct(Orderable):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, null=True)

    sort_order = models.IntegerField(
        null=False,
        blank=False,
        editable=False,
        default=-1,
    )

    @staticmethod
    @receiver(post_init, sender='datahub.TopProduct')
    def post_init(sender, instance, **kwargs):
        if instance.sort_order == -1:
            instance.sort_order = TopProduct.objects.count()
```

the `post_init` step might not be appropriate for the library, but it should set a default value on this field AND updated the linked section to always set an `update_value`
